package com.jass
 
import com.jass.CardGame.Message;
import com.jass.Jass;
import com.jass.CardColours;

dialect "java"
rule "Print Trump Symbols Heart"
    when
        jass : Jass( trumpColour == "HEART" )
    then
        System.out.println( CardColours.HEART.cardSymbol() );
end

rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end

