package com.jass.rules
 
import com.jass.CardGameMain.Message;
import com.jass.JassGame;
import com.jass.CardColours;

global java.util.List list


rule "Print Trump Symbols Heart"
dialect "java"
    when
        t : CardColours ()
    then
        System.out.println( t.cardSymbol() );
        modify(){}
end

// Next player can start round



// Rules
// If a colour is played, all other colours played must match the colour if the players have that colour in their card deck

// If a player has four cards of the same card type in his carddeck, he gets 100 points

// If a player has four jacks in his carddeck he gets 200 points

// If a player has king and queen of the trump colour in his carddeck, he gets 20 points

// If a player has three cards of the same card colour in his carddeck that are in a row, he gets 20 points

// If a player has four cards of the same card colour in his carddeck that are in a row, he gets 50 points

// If a player has five cards of the same card colour in his carddeck that are in a row, he gets 100 points

// A player wins a round if he played the highest card


rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message, myStatus : status )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end

